name: semantic_changelog
description: A continuous deployment tool based on a changelog-first approach (as opposed to relying on commits).
repository: https://github.com/rrousselGit/semantic_changelog
issue_tracker: https://github.com/rrousselGit/semantic_changelog/issues
funding:
  - https://github.com/sponsors/rrousselGit/
version: 1.0.0-dev

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  ansi: ^0.0.1
  args: ^2.4.0
  cli_util: ^0.3.5
  collection: ^1.17.1
  freezed_annotation: ^2.2.0
  http: ^0.13.5
  json_annotation: ^4.8.0
  melos: ^2.9.0
  path: ^1.8.3
  prompts: ^2.0.0
  pub_semver: ^2.1.3
  yaml: ^3.1.1

executables:
  semantic_changelog:
  version: semantic_changelog
dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1
