name: semantic_changelog
description: A continuous deployment tool based on a changelog-first approach (as opposed to relying on commits).
repository: https://github.com/rrousselGit/semantic_changelog
issue_tracker: https://github.com/rrousselGit/semantic_changelog/issues
funding:
  - https://github.com/sponsors/rrousselGit/
version: 1.0.0-dev

environment:
  sdk: ">=2.18.0 <3.0.0"

executables:
  semantic_changelog:
dependencies:
  cli_util: ^0.3.5
  collection: ^1.17.1
  melos: ^2.9.0
  path: ^1.8.3
  pub_semver: ^2.1.3
  yaml: ^3.1.1
